# syntax=docker/dockerfile:1
FROM msai-base
RUN python -c "import os, shutil, site; shutil.move(os.path.join(site.getsitepackages()[0], 'langchainmsai'), os.path.join(site.getsitepackages()[0], 'langchain'))"
COPY . /app
RUN mkdir -p /app/jobs /app/db
RUN mkdir -p /home/jobs
COPY entrypoint.sh /app

# Start and enable SSH
#RUN apt-get update \
#    && apt-get install -y --no-install-recommends dialog \
#    && apt-get install -y --no-install-recommends openssh-server \
#   && echo "root:Docker!" | chpasswd \
#    && chmod u+x ./entrypoint.sh
COPY sshd_config /etc/ssh/

#EXPOSE 8000 2222
#ENTRYPOINT [ "./entrypoint.sh" ]
EXPOSE 8000
# Set root password
RUN echo 'root:Docker!' | chpasswd
CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]

