PERSIST_DIRECTORY: db
MODEL_TYPE: OpenAIChat
# Model type currently can also be LlamaCpp or GPT4All
# MODEL_SUBTYPE: gpt-35-turbo
MODEL_SUBTYPE: GPT4-32
MODEL_TYPE2: default
MODEL_PATH: models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME: text-ada-002

EMBEDDINGS_MODEL_NAME_O: jinaai/jina-embedding-s-en-v1
MODEL_N_CTX: 22000
MODEL_N_BATCH: 8
TARGET_SOURCE_CHUNKS: 1

# Optional example models renamed by removing the _lastpart
EMBEDDINGS_MODEL_NAME_cpu: jinaai/jina-embedding-b-en-v1
EMBEDDINGS_MODEL_NAME_gtr: gtr-t5-large
TEST_EMBEDDINGS_MODEL_NAME: jinaai/jina-embedding-s-en-v1
EMBEDDINGS_MODEL_NAMENEWCHINESE: BAAI/bge-large-en-v1.5

